<?php 
use Zend\Session\Container;
$session = new Container('User');
$first_name =  $session->offsetGet('first_name');
$last_name  =  $session->offsetGet('last_name');
$full_name  =  $first_name . ' ' . $last_name;
$userName   =  $session->offsetGet('userEmail');
$userId     =  $session->offsetGet('userId');

$session_GetAllAccounts = new Container('AllAccounts');
if ($session_GetAllAccounts->offsetExists('Accounts_id')) {
	$Accounts_id   =  $session_GetAllAccounts->offsetGet('Accounts_id');
}
if ($session_GetAllAccounts->offsetExists('Accounts_name')) {
	$Accounts_name   =  $session_GetAllAccounts->offsetGet('Accounts_name');
}
$session_GetAllAdUnits = new Container('GetAllAdUnits');

# Start GenerateColumnChart
$session_GenerateColumnChart = new Container('GenerateColumnChart');
$report  = $session_GenerateColumnChart->offsetGet('GenerateColumnChart_report_all');
$data    = $session_GenerateColumnChart->offsetGet('GenerateColumnChart_report_data_json');
$columns = $session_GenerateColumnChart->offsetGet('GenerateColumnChart_report_data_colum');
$options = $session_GenerateColumnChart->offsetGet('GenerateColumnChart_report_data_options');
$type    = $session_GenerateColumnChart->offsetGet('GenerateColumnChart_report_data_type');
# End GenerateColumnChart

# Start GenerateGeoChart
$session_GenerateGeoChart = new Container('GenerateGeoChart');
$report_GenerateGeoChart  = $session_GenerateGeoChart->offsetGet('GenerateGeoChart_report_all');
$data_GenerateGeoChart    = $session_GenerateGeoChart->offsetGet('GenerateGeoChart_report_all_data_json');
$columns_GenerateGeoChart = $session_GenerateGeoChart->offsetGet('GenerateGeoChart_report_all_data_colum');
$type_GenerateGeoChart    = $session_GenerateGeoChart->offsetGet('GenerateGeoChart_report_all_data_type');
$options_GenerateGeoChart = $session_GenerateGeoChart->offsetGet('GenerateGeoChart_report_all_data_options');
# End GenerateGeoChart

/**
 * Genereate and returns the html code for the chart page.
 * @param mixed $data The data contained in the table
 * @param mixed $columns Description of the table columns
 * @param string $type Required chart type
 * @param mixed $options Options for the chart
 * @return string The html code to that draws the chart
 */
function generateMPChartHtml($data, $columns, $type, $options) {
	$columnsHtml = '';
	if(!empty($columns)){
	foreach ($columns as $column) {
		$columnsHtml .=
		'data.addColumn(\'' . $column[0] . '\', \'' . $column[1] . '\');';
	}
	$page = <<<CHART
<html>
  <head>
    <title>Pie Chart Example</title>
    <script type="text/javascript"
      src='https://www.google.com/jsapi?autoload=
          {"modules":[{"name":"visualization","version":"1"}]}'>
    </script>
  </head>
  <body>
    <div id="vis_div" style="width: 600px; height: 400px;"></div>
    <script type="text/javascript">
      var data = new google.visualization.DataTable();
      $columnsHtml
      data.addRows($data);
      var wrapper = new google.visualization.ChartWrapper({
        chartType: '$type',
        dataTable: data,
        options: $options,
        containerId: 'vis_div'
      });
      wrapper.draw();
    </script>
  </body>
</html>
CHART;
	return $page;
	} # End $columns
	else { $error = 'No Data Report Line Chart'; return $error; }
}
  
?>
<style>
.col-sm-12.text-view { 
    color: #06c;
    text-decoration: none;
    font-size: 12px;
}
</style>
 <div class="container"> 
				    <?php if( $getAccessToken == 1 and $iduser== null and $User_get == null ) { ?>
				    <div class="row"> 
				      <div class="col-sm-12">
				          <ul class="list-group">
							  <li class="list-group-item">
						        <a class="login" href="<?php echo WEBPATH ?>/report-colum-chart"> Report Generate ColumnChart</a> 
						      </li>
						       <li class="list-group-item">
						          <a class="login" href="<?php echo WEBPATH ?>/report-geo-chart"> Report Generate GeoChart</a>
						       </li>
						
						       <li class="list-group-item">
						           <a class="login" href="<?php echo WEBPATH ?>/report-line-chart"> Report Generate LineChart</a>
						       </li>
						
						       <li class="list-group-item">
					        	 <a class="login" href="<?php echo WEBPATH ?>/report-pie-chart"> Report Generate Pie Chart</a>
					           </li>
						
						        <li class="list-group-item">
						            <a class="login" href="<?php echo WEBPATH ?>/report-table-chart"> Report Generate Table Chart</a>
						        </li>  
						  </ul> 
						   </div></div><!-- end Ul->li -->
						   
						   
						 <div class="row"> 
				         <div class="col-sm-6">
				             <?php  print generateMPChartHtml($data, $columns, $type, $options); ?> 
				         </div>   
				         
				         <div class="col-sm-6">
				         
				          <div id="files" data-content-url="<?php echo WEBPATH;?>/adsense/generate-geo-chart">
					        <?php echo $this->partial('generate-geo-chart'); ?>
					      </div>  <!-- end files  --> 
					      
				         </div>  
				         </div> <!-- End Report Line -->
						   
						  <div class="row"> 
				           <div class="col-sm-12">
				            
				           <div class="main-content">
									<div class="file-manager">
									       
									        <div class="row">            
									            <div class="col-lg-12 col-md-12">               
									                <div class="table-responsive">
									                
									                  <div class="container">
												        <h2>Get All AdUnits</h2>
													    <p> View AllGetAllAdUnits of Publisher :  <span class="label label-success"><?php echo $Accounts_id .'-'.$Accounts_name?>.</span></p>
												        </div>
									                    <div id="status_data" class="col-sm-12" ></div> <!--  $('#status_data').html(data);		 -->
									                    <table id="datatable-user-manager" class="table table-sorting table-dark-header datatable">
									                        <thead>
									                            <tr>
									                                <th>Number</th> 
									                                <th>Name</th>     
									                                <th>ID Code</th>   
									                                <th>Status</th>
									                                <th>ACTIVE/INACTIVE</th>
									                                <!--  <th>Action</th> -->
									                                <th>Assign to pub <span class="label label-success"><?php echo $full_name;?></span></th>
									                                <th>Connect Report</th>
									                            </tr>
									                        </thead>
									                        <tbody>
									                           <?php   
									                           # Data GetAllAdUnits 
									                   if($session_GetAllAdUnits->offsetExists('AllAdUnits')){
									                      	$Get_AllAdUnits = $session_GetAllAdUnits->offsetGet('AllAdUnits');
									                           if (!empty($Get_AllAdUnits)) {
									                           	foreach ($Get_AllAdUnits as $adUnit) {
									                           ?>
									                            <tr>
									                                <td> 
									                                   <div class="checkbox">
																		  <input type="checkbox" value=""> 
																		</div>
									                                </td> 
									                                <td>
									                                  <div class="col-sm-12 ">
									                                   <?php echo $adUnit['name'];?>
									                                  </div>
									                                    <div class="col-sm-12 text-view">
									                                      <a href=""><span>Hiden</span></a> |  <a href=""><span>View Report</span></a> |  <a href=""><span>GetCode</span></a>
									                                    </div>
									                                </td>
									                                <td><?php echo  $adUnit['code'];?></td>  
									                                <td id="status<?php echo $adUnit['code']; ?>">
									                                    <?php
									                                    if($adUnit['status']){
									                                        echo '<span class="label label-success"><i class="fa fa-check-circle-o"></i> '.$adUnit['status'].'</span>';
									                                    } else   {
									                                         echo '<span class="label label-danger"><i class="fa fa-minus-circle"></i> Null</span>';
									                                    }
									                                    ?>
									                                </td>
									                                <td>
									                                    <input id="assign<?php echo $adUnit['code']; ?>" 
									                                           onchange="active_usser90(<?php echo $adUnit['code'];?>)" 
									                                           <?php if($adUnit['status']=='ACTIVE'){ echo 'checked';}?> 
									                                           type="checkbox"  
									                                           data-toggle="toggle" 
									                                           data-onstyle="success" 
									                                           data-on="Active"  
									                                           data-off="Pause" 
									                                           data-offstyle="danger" 
									                                           data-size="mini" 
									                                           data-style="ios">
									                                           
									                                    
									                                </td>
									                               <!--    
									                                <td>
									                                    <button class="btn btn-danger btn-xs" onclick="deleteaction90(<?php echo $adUnit['code']; ?>)"><i class="fa fa-trash"></i> Delete</button>
									                                </td>
									                                -->   
									                                 <td>
									                                    <span id="return<?php echo $adUnit['code']; ?>"></span>
									                                    <span   class="btn btn-warning btn-xs"      onclick="assignset('<?php echo $adUnit['code'];?>','<?php echo $userId + Pr_UserId;?>')" ><i class="fa fa-trash"></i>
									                                      <p id="assigntext<?php echo $adUnit['code']; ?>">Assign</p>
									                                    </span>
									                                </td>
									                                
									                                <td>
									                                   <a href="<?php #echo $authUrl; ?>" >
									                                      <button class="btn label label-success btn-xs"  ><i class="fa fa-trash"></i> Connect Report Adsense  </button>
									                                   </a>    
									                                </td>
									                            </tr>
									                           <?php  
									                              } # empty($Get_AllAdUnits)
									                           } else {
									                             	print "No ad units found.\n";
									                            }
									                           } # offsetExists
									                           # End Data GetAllAdUnits 
									                           ?>
									                        </tbody>
									                    </table>
									                </div>
									 
									                 
									            </div>
									        </div>
									    </div>
									</div><!-- end class="main-content" -->
				           
				           
						   </div></div><!-- end Table GetAllAdUnits -->
						   
					<?php }  else if( $getAccessToken == 0 and $iduser== null and $User_get == null ) { 
					  ?>
					    <div class="row"> 
				         <div class="col-sm-12">
					  <?php 
						# Neu Chua co Token thi ket noi den api google de lay token
						echo '<div><div class="request" style="min-height: 300px; margin: 10px;">';
						if (isset($authUrl)) {
							echo '<a class="login" href="' . $authUrl . '">Click for Report Adsense!</a>';
						} else {
							echo '<a class="logout" href="'.WEBPATH.'/users/logout">Logout</a>';
						};
						echo "</div></div>";
					} # end esle
					else if( $getAccessToken == 0 and $iduser != null and $User_get != null ) {
						?>
								    <div class="row"> 
									         <div class="col-sm-12">
										  <?php 
											# Neu Chua co Token thi ket noi den api google de lay token
											echo '<div><div class="request" style="min-height: 300px; margin: 10px;">';
											if (isset($authUrl)) {
												echo "<h3> Hello, Manager : ".$full_name."  </h3>";
												echo '<a class="login" href="' . $authUrl . '">Click Report Adsense For User '.$User_get['first_name'].' '.$User_get['first_name'].'-'.$User_get['last_name'].'</a>';
											} else {
												echo '<a class="logout" href="'.WEBPATH.'/users/logout">Logout</a>';
											};
											echo "</div></div>";
										} # end esle
					?>	  
					
						  
						 </div>
				    
	 </div></div></div> <!--  end Container	 -->	    
 
<script>
    
 var domain = '<?php echo WEBPATH; ?>';
           
$(document).ready(function(){
	 
});

 
function assignset(adunit_id,idu){
    if($('#assign'+adunit_id).prop("checked") === true){
       var active='Assigned';
       $('p#assigntext'+adunit_id).html('<p id="p#assigntext'+adunit_id+'" class="label label-success"><i class="fa fa-check-circle-o"></i> Assigned</p>');
    }else{
           active = 'Not Assign';
           $('p#assigntext'+adunit_id).html('<p id="p#assigntext'+adunit_id+'" class="label label-danger"><i class="fa fa-minus-circle"></i> Not Assign</p>');
    }
     $.ajax({
	   type: "POST",
	   url:  "<?php echo WEBPATH?>/users/assign",
	   data: 'id='+idu+'&adunit_id='+adunit_id+'&status='+active,
	   success: function(data){
		       console.log(" active_usser : " + data);
		       $('#status_data').html(data);
		       $('#return'+adunit_id).html(data);		
			   }
   });
}

 function deleteaction(key) {
              
                $('#cat_id').val(key);
                var URL = "<?php echo WEBPATH?>/user/deleteUser/id/" + key;
                $('#btn-del').html('<a href=' + URL + '> <button type="button" class="btn btn-success" ><span class="glyphicon glyphicon-ok-sign"></span> Yes</button></a>');
                $('#del').modal('show');
            }      
</script>