<?php echo $this->doctype(); 
use Zend\Session\Container;
$session = new Container('User');
$first_name =  $session->offsetGet('first_name');
$last_name  =  $session->offsetGet('last_name');
$full_name  =  $first_name . ' ' . $last_name;
$userName   =  $session->offsetGet('userEmail');
$userId     =  $session->offsetGet('userId');
 
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('1.0 '. $this->translate('ReportAdsense'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>
                        
   
                     
         <style type="text/css">
          .navbar-inverse { 
             background-color: rgba(49,163,68,1) !important; 
             background-image :none;
             border-color: #31a344;
             }
             
           .navbar-brand {
			    float: left;
			    padding: 9px 15px;
			    font-size: 18px;
			    line-height: 20px;
			    color: #fff !important;
			}
			.navbar-inverse .navbar-nav>.active>a {
			    color: #fff;
			    background-color: #31a344 !important;
			    background-image: none;
			    background-repeat: no-repeat;
			    -webkit-box-shadow: navajowhite;
			    box-shadow: none;
			}
			li.pa-right {
				    float: right;
				}
				
				.navbar-inverse .navbar-brand, .navbar-inverse .navbar-nav>li>a {
				    text-shadow: 0 -1px 0 rgb(46, 46, 46);
				}
				.navbar-inverse .navbar-nav>li>a {
				    color: #482e2e;
				}
			p.footer-format {
			    text-align: center;
			    font-size: 16px;
			    font-weight: bold;
			}
			.dropup {
			    margin-top: 6px;
			}	
			/**Menu dropdown*/
			ul.dropdown-menu.menune {
			    display: block;
			    float: right !important;
			    left: 911px;
			    top: 7px;
			    background-color: rgb(49, 163, 68);
			}
        </style>                  

         <?php $this->flashNoty()->fire(); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        
     

 
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img class="log-vavi-bar" src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="ReportAdsense 1.0"/>&nbsp;<?php echo $this->translate('Report Adsense 1.0') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class=""><a href="<?php echo $this->url('home') ?>"> <span class="glyphicon glyphicon-home"></span> <?php echo $this->translate('Home') ?></a></li>
                        <?php if(! $userName ) {?>
                          <li class="active"><a href="<?php echo WEBPATH; ?>/users/login"><span class="glyphicon glyphicon-log-in"></span> <?php echo $this->translate('Login') ?></a></li>
                          <li class=""><a href="<?php echo WEBPATH; ?>/users/register"><span class="glyphicon glyphicon-registration-mark"></span> <?php echo $this->translate('Register') ?></a></li>
                        <?php }else {  # $full_name ?>
                             <li class="active"><a href="#" alt="<?php echo $userName;?>" ><span class="glyphicon glyphicon-check"></span> Hello , <span class="glyphicon glyphicon-user"></span> <?php echo $full_name; ?></a></li>
                             <?php if($userName =='gstearmit@gmail.com' || $userName == 'reportadsense2016@gmail.com' ) { ?>
                              <li class=""><a href="<?php echo WEBPATH; ?>/dashboard-user"><span class="glyphicon glyphicon-off"></span> <?php echo $this->translate('Set Param of ADSENSE') ?></a></li>
                             <?php } # end supper ?>
                             
                              <?php if($userName =='gstearmit@gmail.com' || $userName == 'reportadsense2016@gmail.com' ) { ?>
                                 <!--  
	                                 <ul class="dropdown-menu menune">
								      <li class=""> <a href="<?php echo WEBPATH; ?>/option"><span class="glyphicon glyphicon-cog"></span> <?php echo $userName ?> </a></li>
	                                  <li class=""> <a href="<?php echo WEBPATH; ?>/setpayment"><span class="glyphicon glyphicon-credit-card"></span>  Set PayMent</a></li>
	                              
								    </ul>
							     -->
                              <?php } else { ?>
                                   <li class=""> <a href="#"><span class="glyphicon glyphicon-cog"></span> <?php echo $userName ?> </a></li>
                                   <li class=""> <a href="<?php echo WEBPATH; ?>/setpayment"><span class="glyphicon glyphicon-credit-card"></span>  Set PayMent</a></li>
                                <?php } #end else?>
                              <!--  
                              <li class="pa-right"> 
	                             <div class="dropup">
									  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									    <?php echo $userName ?> <span class="glyphicon glyphicon-cog"></span>
									  </button>
									  <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
									    <li><a href="<?php echo WEBPATH; ?>/option"><?php echo $userName ?> <span class="glyphicon glyphicon-cog"></span></a></li>
									    <li><a href="#">Another action</a></li>
									    <li><a href="#">Something else here</a></li>
									    <li role="separator" class="divider"></li>
									    <li><a href="#">Separated link</a></li>
									  </ul>
								</div>
							</li>
							 -->
							<li class="pa-right"><a href="<?php echo WEBPATH; ?>/users/logout"><span class="glyphicon glyphicon-log-out"></span> <?php echo $this->translate('Logout') ?></a></li>
                            
                              
                        <?php } # End $fire_name?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
         </div> <!-- /container -->
        <div class="container">    
            <hr>
            <footer>
                <p class="footer-format">&copy; 2016 - <?php echo date('Y') ?> by MP Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
