<?php echo $this->doctype(); 
use Zend\Session\Container;
$session = new Container('User');
$first_name =  $session->offsetGet('first_name');
$last_name  =  $session->offsetGet('last_name');
$full_name  =  $first_name . ' ' . $last_name;
$userName   =  $session->offsetGet('userEmail');
$userId     =  $session->offsetGet('userId');
 
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('1.0 '. $this->translate('ReportAdsense'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>
         <style type="text/css">
          .navbar-inverse { 
             background-color: rgba(49,163,68,1) !important; 
             background-image :none;
             border-color: #31a344;
             }
             
           .navbar-brand {
			    float: left;
			    padding: 9px 15px;
			    font-size: 18px;
			    line-height: 20px;
			    color: #fff !important;
			}
			.navbar-inverse .navbar-nav>.active>a {
			    color: #fff;
			    background-color: #31a344 !important;
			    background-image: none;
			    background-repeat: no-repeat;
			    -webkit-box-shadow: navajowhite;
			    box-shadow: none;
			}
			li.pa-right {
				    float: right;
				}
				
				.navbar-inverse .navbar-brand, .navbar-inverse .navbar-nav>li>a {
				    text-shadow: 0 -1px 0 rgb(46, 46, 46);
				}
				.navbar-inverse .navbar-nav>li>a {
				    color: #482e2e;
				}
        </style>                  

         <?php $this->flashNoty()->fire(); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        
     

 
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img class="log-vavi-bar" src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="ReportAdsense 1.0"/>&nbsp;<?php echo $this->translate('Report Adsense 1.0') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class=""><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <?php if(! $userName ) {?>
                          <li class="active"><a href="<?php echo WEBPATH; ?>/users/login"><?php echo $this->translate('login') ?></a></li>
                          <li class=""><a href="<?php echo WEBPATH; ?>/users/register"><?php echo $this->translate('register') ?></a></li>
                        <?php }else {  # $full_name ?>
                             <li class="active"><a href="#" alt="<?php echo $userName;?>" > Hello ,<?php echo $full_name; ?></a></li>
                             <li class=""><a href="<?php echo WEBPATH; ?>/dashboard-user"><?php echo $this->translate('Set Param of ADSENSE') ?></a></li>
                             
                             <!--  
                               <li class=""><a href="<?php echo WEBPATH; ?>/set-param-adsense"><?php echo $this->translate('Set Param of ADSENSE') ?></a></li>
                             -->
                             <li class="pa-right"><a href="<?php echo WEBPATH; ?>/users/logout"><?php echo $this->translate('Logout') ?></a></li>
                        <?php } # End $fire_name?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2016 - <?php echo date('Y') ?> by MP Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
